# ダウンロードするディレクトリ
directory = "./img"
refresh_token = ""
# デフォルトオプション
# 何も入力しなかった場合に適用
option = ""

[folder]
# 機能スイッチ
enable = true
# フォローしているユーザーをフォルダ分け
follow_user = true
# フォルダ分けしたいタグ名を入力
# "<タグ名>"
tag = []
# フォルダ分けしたいユーザーのIDを入力
# <ID>
user = []
# タグ名､表記揺れのタグ名を入力
# {tag = "<タグ名>", vague = ["<表記揺れタグ名>"]}
vague = []

[ignore]
enable = true

# ダウンロードしないタグ名を入力
# "<タグ名>"
tag = []
# ダウンロードしないユーザーのIDを入力
# <ID>
user = []

[ignore.ai_illust]
# AIイラストをダウンロードしないようにする
enable = true
# フォローしているユーザーのAIイラストはダウンロードする
follow_user = true

[ugoira2gif]
enable = true
# スレッドとして処理するか
thread = true
# フォーマット名を入力
# webp,gif,apngのみ対応
# 上記フォーマット以外､または未入力の場合は無効
format = "gif"

[notification]
enable = true

[notification.report]
enable = true
# 進捗を通知する際のインターバル
# 分単位
interval = 60

[notification.desktop]
enable = true

[notification.discord]
enable = false
# webhookのurlを入力
# 未入力の場合は無効
webhookUrl = ""

[notification.discord.mention]
enable = false
# 自分のIDを入力することでメンションが可能
# 未入力の場合は無効
discordId = ""